version: '3.7'
services:
  api:
    build:
      context: .
    image: api
    depends_on:
      - jaeger
      - prometheus
      - mongodb
    container_name: api
    ports:
      - "${APPLICATION_PORT:-3001}:${APPLICATION_PORT:-3001}"
      - "${METRICS_PORT:-3002}:${METRICS_PORT:-3002}"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongodb:${MONGODB_PORT:-27017}/booksland?replicaSet=rs0
      - APPLICATION_PORT=${APPLICATION_PORT:-3001}
      - METRICS_PORT=${METRICS_PORT:-3002}
      - OTLP_EXPORTER_HOST=${OTLP_EXPORTER_HOST:-jaeger}
      - OTLP_EXPORTER_PORT=${OTLP_EXPORTER_PORT:-4318}
      - BASE_URL=${BASE_URL:-http://localhost}:${APPLICATION_PORT:-3001}
    networks:
      - booksnet
  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_VERSION:-latest}
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "${OTLP_EXPORTER_PORT:-4318}:${OTLP_EXPORTER_PORT:-4318}"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
    networks:
      - booksnet
  mongodb:
    image: mongo:6
    container_name: mongodb
    command: [--replSet, rs0, --bind_ip_all, --port, "${MONGODB_PORT:-27017}"]
    ports:
      - "${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}"
    restart: unless-stopped
    healthcheck:
      test: test $$(mongosh --port ${MONGODB_PORT:-27017} --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:${MONGODB_PORT:-27017}\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
    networks:
      - booksnet
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - PROMETHEUS_HOST=${PROMETHEUS_HOST:-prometheus}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT:-9090}
      - APPLICATION_PORT=${APPLICATION_PORT:-3001}
    ports:
      - "${PROMETHEUS_PORT:-9090}:${PROMETHEUS_PORT:-9090}"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - booksnet
networks:
  booksnet: